#MySQL \uC14B\uD305
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/global_assets_db
    username: ${DB_USER}
    password: ${DB_PW}

 # ALWAYS : NEVER
  sql:
    init:
      mode: NEVER
  jpa:
    # TRUE : FALSE
    defer-datasource-initialization: false
    hibernate:
      #Supported values include 'create', 'create-drop', 'create-only', 'drop', 'update', 'none' and 'validate'
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# ====== FX 소스 (Twelve Data) ======
#twelve:
#  base-url: https://api.twelvedata.com
#  api-key: a5b673b9653843499ecc1d8f3123b87f
#
#twelvedata:
#  apikey: ${twelve.api-key}
#  base-url: ${twelve.base-url}
## ====== Naver Search Open API (News) ======
#
#naver:
#  search:
#    news-url: https://openapi.naver.com/v1/search/news.json
#    client-id: 0QqTJMTTyd2KdMtH9U01
#    client-secret: NYYp04bH9C
#=======
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}
