#MySQL \uC14B\uD305
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/global_assets_db
    username: ${DB_USER}
    password: ${DB_PW}

 # ALWAYS : NEVER
  sql:
    init:
      mode: NEVER
  jpa:
    # TRUE : FALSE
    defer-datasource-initialization: false
    hibernate:
      #Supported values include 'create', 'create-drop', 'create-only', 'drop', 'update', 'none' and 'validate'
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}